# Generated by Django 4.1 on 2022-09-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10)),
                ('Transport', models.CharField(max_length=100)),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Station', models.CharField(max_length=100)),
                ('District_Name', models.CharField(max_length=200)),
                ('Neighborhood_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
