# Generated by Django 4.1 on 2022-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_alter_transport_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
            ],
        ),
    ]
